### ISSUE TITLE
Throw WARNING for "OK: Got first data sample"

### ISSUE THREAD

**Issue by gopi-ar** [mclarkson/check_iftraffic_nrpe.sh#4]
We still get `OK: Got first data sample.` on some of our Ubuntu 14.04 hosts the first time this runs; it doesn't go away until we call this file locally (i.e. not via NRPE).

This would be much easier to spot and debug if it returned `WARNING` or `CRITICAL`

**Comment by gopi-ar** [comment]
Somehow the NRPE wasn't able to create the file under /var/tmp, though calling the command directly did this. I copied the file created for `root` user manually, and now it works.

`mv touch /var/tmp/check_iftraffic_nrpe_sh..root.cache /var/tmp/check_iftraffic_nrpe_sh..nagios.cache`

Any idea why creation is failing via nrpe?

**Comment by mclarkson** [comment]
I've added an option, '-u'. If used it will change unknown errors to warning errors.
I have not tested it so please let me know if it works for you.

Thanks for the feedback!

**Comment by mclarkson** [comment]
Reopened waiting for feedback...

**Comment by gopi-ar** [comment]
Unfortunately, it still says OK if it isn't able to create the file in `/var/tmp`..

**Comment by mclarkson** [comment]
I didn't understand the problem properly. For some reason I thought it was returning 'Unknown' error, even though you didn't say that! I've added a check for the write directory, which will return 'Unknown' error unless '-u' is used.

Note that 'OK: Got first data sample' will still return an OK status since getting the first data sample will happen every time the stats roll back around to zero.

**Comment by davidak** [comment]
On Ubuntu 12.04 /var/tmp is also owned by root, so user nagios (nrpe) can't create files there.

Could you use /tmp instead?

**Comment by mclarkson** [comment]
Looks like this is fixed. Closing.
