### ISSUE TITLE
I get "Cannot access '/sys/class/net'. Proc or sys not mounted?"

### ISSUE THREAD

**Issue by gopi-ar** [mclarkson/check_iftraffic_nrpe.sh#7]
I get this error even though I have full access to this script and the directory `/sys/class/net` has `777` access. If I run the script locally as root (not via NRPE), it works but on NRPE, I get this error. I had to give NRPE root access on Ubuntu 14.04 to make this run via NRPE.

This is strange because it worked in all other servers without root; am I missing something?

**Comment by mclarkson** [comment]
/sys/class/net should be 755 rather than 777 - check your other servers to see what they are; there might be something weird going on with your /sys mount, so check /etc/fstab for /sys against the other servers too. Apart from that I can only think of selinux or apparmour denying a read on a 777 file, but, like you say, it should work fine without root.
